# Generated by Django 2.2.6 on 2020-11-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0002_auto_20170927_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('name', models.CharField(max_length=190, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
    ]
